<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>Icon.png</PackageIcon>
    <Version>1.0.0</Version>
    <Description>A strong and fast library to parse and evaluate formulas. It also supports custom formulas. This library is built using 'DevBrewLabs.Parserly' library.
</Description>
    <Company>DevBrewLabs</Company>
    <IncludeSymbols>False</IncludeSymbols>
    <SignAssembly>False</SignAssembly>
    <Authors>DevBrewLabs</Authors>
    <PackageTags>alpha;parse;parser;engines;formula;Evalis.formula;formula engine; DevBrewLabs.Evalis;</PackageTags>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/kartikdeepsagar/DevBrewLabs.Evalis</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CS1591;NU1701</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CS1591;NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icon.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Formulas.md" Link="Formulas.md" />
    <None Include="..\..\README.md" Link="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevBrewLabs.Parserly" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\EngineResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EngineResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\FormulaResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FormulaResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\EngineResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>EngineResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\FormulaResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FormulaResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
